
# sshMakeConfig
sshMakeConfig() {
  echo '# AUTOGENERATED by sshMakeConfig()' >~/.ssh/config
  for i in ~/.ssh/config.d/*; do
    echo "#${i}" | tee -a ~/.ssh/config
    cat ${i} >>~/.ssh/config
  done
}
